model_list = [
    "bert-base-uncased",
    "distilbert-base-uncased",
    "bert-base-multilingual-uncased",
    "camembert-base",
    "camembert/camembert-large",
    "camembert/camembert-base-ccnet",
    "camembert/camembert-base-ccnet-4gb",
    "camembert/camembert-base-oscar-4gb",
    "camembert/camembert-base-wikipedia-4gb",
    "flaubert/flaubert_small_cased",
    "flaubert/flaubert_base_uncased",
    "flaubert/flaubert_base_cased",
    "flaubert/flaubert_large_cased",
]
